repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: pylint-errors-only
        name: pylint (errors-only)
        entry: python -m pylint --errors-only dexamine
        language: system
        pass_filenames: false

      - id: pytest
        name: pytest
        entry: python -m pytest dexamine/
        language: system
        pass_filenames: false

