[tool.poetry]
name = "dexamine"
version = "0.1.0"
description = "Examine DEX data from Ethereum archive nodes."
authors = ["Magnus Hansson <hansson.carl.magnus@gmail.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
web3 = "^6.15.0"
pandas = "^2.2.0"
py-evm = "^0.8.0b1"
eth-abi = "^5.0.0"
pylint = "^3.0.3"
black = "^24.1.1"
pytest = "^8.0.0"
pyarrow = "^15.0.0"
mypy = "^1.8.0"
types-requests = "^2.31.0.20240125"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
