name: pytest and pylint

on:
  push:
    branches: [main]

jobs:
  tests-and-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Cache Poetry installation
      uses: actions/cache@v4
      with:
        path: ~/.local/bin
        key: poetry-${{ runner.os }}-1.7.1

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Configure Poetry
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true

    - name: Cache dependencies
      uses: actions/cache@v4
      with:
        path: .venv
        key: ${{ runner.os }}-py-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-py-

    - name: Install dependencies for caching
      run: |
        poetry install --no-interaction --no-root

    - name: Install my package
      run: |
        poetry install --no-interaction

    - name: Run pytest
      run: |
        poetry run pytest dexamine/

    - name: Run pylint
      run: |
        poetry run pylint --errors-only dexamine/
